twist_mux:
  ros__parameters:
    topics:
      # Nav2 com prioridade baixa
      navigation:
        topic: /turtlebot1/cmd_vel_nav
        timeout: 0.5
        priority: 10

      # YOLOv8 com prioridade alta
      vision_security:
        topic: /turtlebot1/cmd_vel_vision
        timeout: 0.5
        priority: 100